// ランタイム状態変数（全ファイルで共有）
var origSoftcapEnabled = false;
var isEscalationMode   = false;
var isCameraAutoZoom   = true;
var escalationTimer    = null;
var spectatorTargetId  = null;
var isClientMode       = false;
var hostConn           = null;
var clipPlanes         = [];
var clientActiveCollisions = new Set();
var remotePlayerParticipation = {};
var localPlayerParticipation  = true;
var ballBody, sphere, ballShadow;
var isOriginalActive   = false;
var cameraMode         = 'DEFAULT';
var camYaw = 0, camPitch = 0;
var isPointerLocked    = false;
var touchCamId = null, lastTouchCamX = 0, lastTouchCamY = 0;
var aiEntities         = [];
var aiCounter          = 0;
var remoteEntities     = {};
var remotePlayerTeams  = {};
var pendingSpawnList   = [];
var isSurvivalMode     = false;
var isKnockbackMode    = false;
var initialLives       = 3;
var knockbackRate      = 1.0;
var knockbackExponent  = 2.0;
var isCustomMatchActive = false;
var localPlayerParticipation_saved = null;
var isMatchParticipant = true;
var playerTeam         = "none";
var isHostMode         = false;
var myPeer = null, myPeerId = "offline_player", peer = null;
var defaultParamsBackup = null;
var originalModeLight  = null;
var networkLatency = 0; // レイテンシ補正用
var lastSettingsSyncTime = 0; // 設定の定期同期タイマー
var selfSync = { ts: 0, pos: new THREE.Vector3(0, 50, 0), vel: new THREE.Vector3() };
var activeConns = [];
var LOBBY_PREFIX = "KINTA3D_WIFI_";
var lastPlayerStress   = null;
var lastPlayerLives    = null;
var remotePlayerParticipation = {};
var playerSpriteObj = { _spriteRes: null, lastDisplayName: "", lastKills: -1, lastLives: -1, lastStress: -1, lastModeKey: "" };
var sharedSphereGeom, sharedShadowGeom, stadiumBodies = [], stadiumMeshes = [], effects = [];
var restartTimer = null, resetTimer = null;
var scene, camera, renderer, world, dirLight, shadowLight;
var lastTime, frameTime = 1000 / 60;
var _tempVector, _tempHV, _gcBodies = [], _gcIds = [], _allBodies = [];
var maxSpeedSq;
var SPRITE_W = 1280, SPRITE_H = 160, SPRITE_FONT = "68px VT323, DotGothic16, monospace";
